[package]
name = "rusty_winapi"
version = "0.1.0"
authors = ["Alexey V. Litvinov <lialsoftlab@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
